// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfSfh-d2uJd1UPO2qopdAV7sBpEAwXy0',
    appId: '1:686038024705:web:19696cd6f679b0c93ab600',
    messagingSenderId: '686038024705',
    projectId: 'parkdata-12c63',
    authDomain: 'parkdata-12c63.firebaseapp.com',
    storageBucket: 'parkdata-12c63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl9HUG4LeSqlx8bndBIlY3gGH_YfC52uM',
    appId: '1:686038024705:android:53483465e00e96923ab600',
    messagingSenderId: '686038024705',
    projectId: 'parkdata-12c63',
    storageBucket: 'parkdata-12c63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPCB8R-1jET0b_k-xaETksSbGw7VwV9UU',
    appId: '1:686038024705:ios:96aa2e212e96b5863ab600',
    messagingSenderId: '686038024705',
    projectId: 'parkdata-12c63',
    storageBucket: 'parkdata-12c63.appspot.com',
    iosBundleId: 'com.example.parkIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPCB8R-1jET0b_k-xaETksSbGw7VwV9UU',
    appId: '1:686038024705:ios:16193baced468a443ab600',
    messagingSenderId: '686038024705',
    projectId: 'parkdata-12c63',
    storageBucket: 'parkdata-12c63.appspot.com',
    iosBundleId: 'com.example.parkIt.RunnerTests',
  );
}
